### ISSUE TITLE
Parsing seems to break with ternary in attribute

### ISSUE THREAD

**Issue by failpunk** [natewallace/angular2-inline#25] opened 2017-07-10 20:56 UTC
You can see the syntax highlighting breaks in the following the line:
`[routerLink]="selected.services.length ? '/payment' : null"`

<img width="514" alt="screen shot 2017-07-10 at 1 54 30 pm" src="https://user-images.githubusercontent.com/1109167/28039480-52c30fc4-6577-11e7-9a36-5d595ea2fb72.png">

This is legal template syntax but is not highlighted correctly.

**Comment by natewallace** [comment] 2017-07-13 19:23
This is a duplicate of issue #14

**Closed as completed by natewallace** 2017-07-13 19:23 UTC
