### ISSUE TITLE
string detection vs ternary expressions

### ISSUE THREAD

**Issue by mlavoie87** [natewallace/angular2-inline#15] opened 2017-02-27 17:07 UTC
It seems that when I use ternary expressions inside of an attribute, the string detection gets screwed up at a certain point but not every time... 

Highlight is fine on that one...
![capture d ecran 2017-02-27 a 12 01 58](https://cloud.githubusercontent.com/assets/16900238/23371139/1be10d6c-fce5-11e6-98d8-361acf3a8f24.png)

But seems to go on and off on that one...
![capture d ecran 2017-02-27 a 12 08 20](https://cloud.githubusercontent.com/assets/16900238/23371242/751f37a0-fce5-11e6-8c93-e3a957d0ba60.png)

**Comment by mlavoie87** [comment] 2017-02-27 17:52
After further look, I found out that the ternary operator expressions (lines 51 and 64) seem to cause the problem.

**Comment by natewallace** [comment] 2017-03-02 23:21
This is a duplicate of issue #14

**Closed as completed by natewallace** 2017-03-02 23:21 UTC
